### ISSUE TITLE
Did some translations to Korean

### ISSUE THREAD

**Issue by codeanddonuts** [dwmkerr/hacker-laws#114]
[한국어 / Korean] https://github.com/codeanddonuts/hacker-laws-kr

This repo seems promising, so I did some translation jobs.

**Comment by dwmkerr** [comment]
This is awesome! Can you help me make sure that I have written the link properly?

The PR is: #115

I had to google how to write 'korean' in korean, and want to make sure it's correct! Thanks very much btw, share you twitter handle/linkedin if you want me to mention you when I share this update!
