### ISSUE TITLE
Turkish Translations

### ISSUE THREAD

**Issue by umutphp** [dwmkerr/hacker-laws#122]
The repo is very cool and inspiring. I has translated it to Turkish.

https://github.com/umutphp/hacker-laws-tr

**Comment by dwmkerr** [comment]
Awesome! Is my google translate of 'Turkish' correct?

Türkçe / Turkish Version

**Comment by umutphp** [comment]
Yes, it is correct.

**Comment by dwmkerr** [comment]
Thanks!
