### ISSUE TITLE
Brazilian Portuguese Translate

### ISSUE THREAD

**Issue by LeoFC97** [dwmkerr/hacker-laws#126]
I'm working on the PT-BR (Brazilian-Portuguese) translation.

https://github.com/leonardofernandescosta/hacker-laws-ptbr

**Comment by dwmkerr** [comment]
Ace! Is it ready for me to link and share?

**Comment by LeoFC97** [comment]
Working in progress

**Comment by dwmkerr** [comment]
Awesome, let me know when I can share! BTW, I am thinking of integrating:

https://gitlocalize.com

Do you think this would be useful to manage the localisations?

**Comment by LeoFC97** [comment]
I nerver used gitlocalize, but its always good to trey new stuff.

**Comment by dwmkerr** [comment]
OK cool, then let's give it a try! I will set it up now and we can see if it is easy to work with. I think the thing I am keen to see if it can handle is how do we _update_ translations when new content comes into master, i.e. how would we know what text has changed and therefore what translations to update! Just about to try it now

**Comment by LeoFC97** [comment]
Ok, almost finishing the translation

**Comment by dwmkerr** [comment]
OK buddy, ready to give it a try!

![image](https://user-images.githubusercontent.com/1926984/60150569-d2c99800-980b-11e9-9db6-05d4b2c85e17.png)

Can you try logging into https://gitlocalize.com, then once you do so let me know your username? Then I can add you to the team and we can see how it works!

**Comment by LeoFC97** [comment]
leofc97 is my username there.

**Comment by dwmkerr** [comment]
OK! I think you are now the moderator for `pt-BR`. But this is my first time with the tool so am learning too :lol:

**Comment by dwmkerr** [comment]
cc @umutphp

**Comment by umutphp** [comment]
I have also logged in to GitLocalize. My username is umutphp. You can add me as the moderator of Turkish

**Comment by LeoFC97** [comment]
I'm working on the GitLocalize, but i cant see where i cant upload my readme.md file (translated to pt-br). The only option that I have is to translate again, and it will take much more time. 
![image](https://user-images.githubusercontent.com/33994116/60209670-86914e80-9831-11e9-96f5-a0e97e920a6f.png)

**Comment by dwmkerr** [comment]
@umutphp i've made you a moderator - @LeoFC97 let me take a look and see what I can do!

**Comment by dwmkerr** [comment]
@LeoFC97 can you try creating a small review request with what you have? I think then we will get a PR with the markdown, and then I _think_ we can actually manually add your whole translation to the PR and I hope then it'll just incorporate it

**Comment by umutphp** [comment]
@dwmkerr I think we can not create a review request without finishing the 100% of the translation. So We should either finish the translation by copy/paste on GitLocalize or create the translations/locale.md file manually. 

I preferred to use GitLocalize to use and get familiar with the tool :)

**Comment by dwmkerr** [comment]
Ah I see!

**Comment by umutphp** [comment]
Hi @dwmkerr 

I have almost finished entering the Turkish translations to GitLocalize but I can not edit the lists at the beginning of the page. So I can not create Review Request to finish the process.

If it is a bug of GitLocalize, maybe we can change the format of the list.

**Comment by LeoFC97** [comment]
@umutphp  how can i create the locale.md manually? I dindn't find this feature.

**Comment by dwmkerr** [comment]
I think you'd literally make a PR to create:

```
translations/pt-BR.md
```

And that would do it!

**Comment by dwmkerr** [comment]
Under the hood, I think that this is all that the tool will do; if it is smart enough to pick up on presence of the file having been manually added, it might just work. What I am hoping is that when the text then changes in the future, it's easy to see what the translation work would be required.

**Comment by LeoFC97** [comment]
I need permision to create a new branch(feat/ptbr-version)

![image](https://user-images.githubusercontent.com/33994116/60287002-34126980-98e7-11e9-9fb7-77eb0168bc9c.png)

**Comment by dwmkerr** [comment]
If you create a PR I’ll just merge directly into master from that for now!

**Comment by LeoFC97** [comment]
Right, sorry about the confusion. I'm kinda new to github :cold_sweat:

PR #127

**Comment by umutphp** [comment]
> @umutphp how can i create the locale.md manually? I dindn't find this feature.

The MD file per locale can be created on the Github repo, not on GitLocalize.

**Comment by umutphp** [comment]
I have created a ticket to GitLocalize about the problem in nested lists that I mentioned before. They replied and said that they were aware of it and their dev team  is working on fixing it.


> Hi @dwmkerr
> 
> I have almost finished entering the Turkish translations to GitLocalize but I can not edit the lists at the beginning of the page. So I can not create Review Request to finish the process.
> 
> If it is a bug of GitLocalize, maybe we can change the format of the list.

**Comment by umutphp** [comment]
@dwmkerr 
They have resolved the issue :) and I could finish the translation. PR is also created :)

**Comment by dwmkerr** [comment]
Awesome!

**Comment by dwmkerr** [comment]
@umutphp I'm hoping that if text _changes_ then we'll see that in GitLocalise too, fingers crossed!

**Comment by umutphp** [comment]
@dwmkerr I have faced another issue in GitLocalize. As I translated the titles of sections, the anchors also changed. So the links are not working in [translations/tr.md](tr.md) file. The URLs in the links should also be translatable. I have raised a ticket for it.

**Comment by dwmkerr** [comment]
OK sounds good. I've also raised a few questions on 'mass translation' with an existing MD file, and how changes/deletions are handled with the original text..

**Comment by umutphp** [comment]
@dwmkerr GitLocalize sends an email when the original file is updated. 

![image](https://user-images.githubusercontent.com/3245166/60506255-29cce280-9cce-11e9-9da2-cc162fc083b1.png)

**Comment by dwmkerr** [comment]
Oh that's cool, thanks for letting me know!

**Comment by dwmkerr** [comment]
#130  - FYI I'll update the contributor guide with info on localisation as we get more familiar with it!

**Comment by dwmkerr** [comment]
FYI we have a Brazilian Portuguese translation now, so closing this, but if @LeoFC97 you want to contribute to it give me a shout and I'll add you as a contributor!
