### ISSUE TITLE
Boy Scout Rule

### ISSUE THREAD

**Issue by dwmkerr** [dwmkerr/hacker-laws#144]
> Leave your code better than you found it.

https://deviq.com/boy-scout-rule/

**Comment by tillchen** [comment]
It's a great rule!

**Comment by umutphp** [comment]
I also think it is a great rule. It is very close to the notification message ("Leave it how you want to find") commonly used for public toilets in Turkey. So, It made me smile :)

**Comment by dwmkerr** [comment]
It's also commonly attributed to Uncle Bob so I think passes the test of coming from a good source 😄  I might add this one this week
