### ISSUE TITLE
Goodhart's law

### ISSUE THREAD

**Issue by rohitchormale** [dwmkerr/hacker-laws#148]
[Law says](https://en.wikipedia.org/wiki/Goodhart%27s_law),

> Any observed statistical regularity will tend to collapse once pressure is placed upon it for control purposes.

In [this](https://arxiv.org/abs/1809.07841) paper, authors tried to apply it to very interesting use case.

**Comment by avimar** [comment]
More accessible:
>"When a measure becomes a target, it ceases to be a good measure."
>—  Goodhart’s Law

Pretty nice writeup: https://coffeeandjunk.com/goodharts-campbells-law/

**Comment by dwmkerr** [comment]
Nice suggestion will look into adding this too!

**Comment by rohitchormale** [comment]
> More accessible:
> 
> > "When a measure becomes a target, it ceases to be a good measure."
> > —  Goodhart’s Law
> 
> Pretty nice writeup: https://coffeeandjunk.com/goodharts-campbells-law/

Thanks for link. Good read.
