### ISSUE TITLE
Principle of least astonisment

### ISSUE THREAD

**Issue by lonetwin** [dwmkerr/hacker-laws#181]
> If a necessary feature has a high astonishment factor, it may be necessary to redesign the feature.
>
> Textbook formalization: People are part of the system. The design should match the user's experience, expectations, and mental models.

[Source](https://en.wikipedia.org/wiki/Principle_of_least_astonishment)

**Comment by dwmkerr** [comment]
Makes a lot of sense I'd add https://en.wikipedia.org/wiki/Convention_over_configuration as well, will create an issue for that
