### ISSUE TITLE
feat: Hacker Laws CLI

### ISSUE THREAD

**Issue by dwmkerr** [dwmkerr/hacker-laws#198]
A simple CLI (as a separate repo) which can:

1. Show a random law
2. List laws
3. "announce" a law, by firing it up to twitter, LI, reddit etc

Point 3 would speed up the process of sharing updates.

**Comment by umutphp** [comment]
Hi @dwmkerr;
I have two questions about this issue :)

- Do you want to do it on your own or ask for contribution?
- What do you think about having a simple web site (showing random law on home page, a list page and share buttons for all laws) instead of CLI?

**Comment by srijanshetty** [comment]
@dwmkerr, I agree with @umutphp. I like how http://cheat.sh/ works, you just curl a webpage and get plaintext data and leaves the user with an optionality to use their favorite client to get information.

**Comment by dwmkerr** [comment]
@umutphp totally happy for a contribution! @srijanshetty agreed, I love how `cheat.sh` works. I'll take a look at domain names but in the meantime happy for anyone to suggest a simple design for how we would structure it in the code (I've done a few static sites based on Hugo now which have been easy to work with, but if we want a `curl`-able site a simple web server might be needed to handle the user agent type appropriately)

**Comment by umutphp** [comment]
Hi @dwmkerr,
As far as I know, HUGO (you said that you are familiar with) can be configured to serve content in multiple output formats (HTML and JSON together). We can create a simple site with a home page listing all the laws, detail pages for all laws and JSON api end points for the two type of pages. 

For CLI, I suggest to implement it so it fetches the list of laws and shows a random law. A simple file cache will be cool not to show error after a network failures.

If you want to do the social announcements as one for all, the cli can be extended to do so. But if not, the detail page can include social share buttons.

PS: I checked the themes section in the official site of HUGO, [Binario](https://themes.gohugo.io/binario/) seems simple and nice :).

**Comment by 1t1e1** [comment]
Hi. I want to learn and eventually get a job. I like this issue.

I wrote a simple server with instinct [here](https://github.com/1t1e1/hacker-laws-server) 

I examined HUGO a little bit. I want to do it.

**Comment by darekkay** [comment]
> A simple CLI (as a separate repo) which can:
> 1. Show a random law

For this use case, I have created [Tip of the Day](https://tips.darekkay.com/html/hacker-laws-en.html) - you can view one random (shuffled) hacker law/principle per day (HTML, JSON, RSS).

**Comment by umutphp** [comment]
> A simple CLI (as a separate repo) which can:
> 
> 1. Show a random law
> 2. List laws
> 3. "announce" a law, by firing it up to twitter, LI, reddit etc
> 
> Point 3 would speed up the process of sharing updates.

Hi @dwmkerr and All,

I have finished implementing a simple CLI (with Go to show my excellent skills :) ) which covers the first and second requirements. All kind of feedbacks and contributions are welcomed.

Repo: [https://github.com/umutphp/hacker-laws-cli](https://github.com/umutphp/hacker-laws-cli)

**Comment by dwmkerr** [comment]
Looks really cool! I'm going to add a link and a screenshot to the main repo so people can see where to get it and then I think we can close this issue! I'll also share an update on this 😄
