### ISSUE TITLE
Hick–Hyman Law

### ISSUE THREAD

**Issue by csparpa** [dwmkerr/hacker-laws#205]
Decision time grows logarithmically with the number of options you can choose from:

![image](https://user-images.githubusercontent.com/5172190/73918386-d7861c80-48c1-11ea-98cf-fde81324c2f4.png)

This relates to cognitive information capacity

https://en.wikipedia.org/wiki/Hick%27s_law

**Comment by puremana** [comment]
Your explanation turned out to express the law beautifully in such a simple manner. I hope you don't mind me using it.

Interesting law. Relates somewhat to the previous law I did, Fitts law, which was quite surprising.
Thanks!

**Comment by dwmkerr** [comment]
Agreed! Thanks for the pull request @puremana and the suggestion @csparpa, will merge this one in today!
