### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by KevinBockelandt** [dwmkerr/hacker-laws#225]
I took a look on [GitLocalize](https://gitlocalize.com/repo/2513) to help with the French translation but it seems I cannot create a new language entry myself.

Can you add me if you're interested?

**Comment by dwmkerr** [comment]
Awesome, thanks @KevinBockelandt! I've just made you the language admin :)

![Uploading image.png…]()

**Comment by KevinBockelandt** [comment]
Translation is now [done and online](https://github.com/dwmkerr/hacker-laws/blob/master/translations/fr.md), so I guess we can close the issue :)

**Comment by dwmkerr** [comment]
Awesome, thanks @KevinBockelandt!
