### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by viktodergunov** [dwmkerr/hacker-laws#227]
Hey, I would like to make a German Translation. 
Could you add me if you're interested?

**Comment by dwmkerr** [comment]
Awesome! I've made you the `de` admin, thanks so much @viktodergunov!

**Comment by dwmkerr** [comment]
![image](https://user-images.githubusercontent.com/1926984/74997150-6da86e00-5490-11ea-8976-fc601a390985.png)

**Comment by TheBusyBiscuit** [comment]
Since there hasn't been much activity on this language, I have taken the liberty to do a few translations myself already.
I will probably contribute a few translations every so often but it can take quite a while to finish.

I am just letting you know :)

**Comment by dwmkerr** [comment]
Great! Just give me a shout if anything needed :)

**Comment by dwmkerr** [comment]
Looks like there's not much activity here so closing the issue, if there are any issues with translations feel free to open a new one!

**Comment by cblte** [comment]
Hello. I also would like to support this, but it seems to be that viktodergunov has done much work on this.

**Comment by dwmkerr** [comment]
Hi @cblte I've added you as a translator - if you need moderator access and it's ok with the others the just let me know!!
