### ISSUE TITLE
Daily law/principle

### ISSUE THREAD

**Issue by darekkay** [dwmkerr/hacker-laws#229]
Thank you very much for this project. I've included the laws/principles in my [Tip of the Day](https://tips.darekkay.com/html/hacker-laws-en.html) project. It displays one random (shuffled) law/principle per day (HTML, JSON, RSS). If you think it's worth including it in your project's README, I would create a pull request. Otherwise, you may just close this issue :)

**Comment by dwmkerr** [comment]
That's awesome, I'd love to include it in the README! Please do go ahead and go for it with a PR, feel free to take a call on where makes sense, I'll merge so you are in the contributors list (I want to add a proper 'contributors' section!) then I can shuffle it around if needed!

**Comment by darekkay** [comment]
Thanks! I've created a [PR](https://github.com/dwmkerr/hacker-laws/pull/243).
