### ISSUE TITLE
Typo in “The Open/Closed Principle”

### ISSUE THREAD

**Issue by peternlewis** [dwmkerr/hacker-laws#233]
I'm not sure entirely what this is supposed to be saying, but it isn't this:

> If the module could not be modified by a consumer so that now existing Markdown features are handled, then it would be closed for modification.

**Comment by puremana** [comment]
The spelling and grammar is correct, but I agree that it is a confusing statement

**Comment by dwmkerr** [comment]
What about this? #275

As a hypothetical example, imagine a module which is able to turn a Markdown document into HTML. Now imagine there is a new syntax added to the Markdown specification, which adds support for mathematical equations. The module should be _open to extension_ to implement the new mathematics syntax. However, existing syntax implementations (like paragraphs, bullets, etc) should be _closed for modification_. They already work, we don't want people to change them.

**Comment by peternlewis** [comment]
Sounds a lot clearer to me.

**Comment by dwmkerr** [comment]
Cool, wanted a second pair of eyes, appreciate the review @peternlewis will merge and close :)
