### ISSUE TITLE
Ebook from hacker laws content

### ISSUE THREAD

**Issue by Glyphack** [dwmkerr/hacker-laws#260]
I was thinking is there any ebook version of this repo for reading on ebook readers available?

**Comment by umutphp** [comment]
Hi @Glyphack and @dwmkerr,

I had some time (thanks to covid-19 lockdown) to make a quick PDF generation by using `pandoc` command. The result is attached.
[hacker-laws.pdf](https://github.com/dwmkerr/hacker-laws/files/4372074/hacker-laws.pdf)

I have removed the table of content section and translation sections from README before executing the following command. 

```bash
pandoc  -V toc-title:"Table Of Contents" --toc --pdf-engine=xelatex -s -o hacker-laws.pdf README-modified.md
```

**Comment by igbanam** [comment]
This is amazing. Thank you ❤️

**Comment by dwmkerr** [comment]
![image](https://user-images.githubusercontent.com/1926984/84231614-1acaf300-ab21-11ea-9bc0-4293b36537c4.png)

I've also added a script in the assets folder which generates the ebook. It's a little dirty, but I might do something like add it as a release automatically on a push to master, if people would find it useful1

**Comment by AnimMouse** [comment]
Hi! I have just created an [automated PDF ebook creator](https://github.com/AnimMouse/hacker-laws-ebook) using GitHub actions using the script in assets.

**Comment by dwmkerr** [comment]
Note: still need to link to the ebook in the main readme. Thanks all who commented on this thread - the setup now works like this:

- All pull requests will at least verify that the ebook _can_ be created
- If I push a version tag it'll create a new release with the ebook attached

All that is left is to link to the releases or latest ebook in the main readme and share this on social media :smile:

**Comment by dwmkerr** [comment]
This is done now!
