### ISSUE TITLE
Want to help

### ISSUE THREAD

**Issue by eugenioamn** [dwmkerr/hacker-laws#262]
Hello!

If possible, I would like to help translating and updating the repository to portuguese (Brazil). Also, I've made some corrections and sent a pull request.

**Comment by dwmkerr** [comment]
Sure thing @eugenioamn! If you Log On to 'GitLocalise' and let me know when you are done, I can make you a moderator of the Brazilian translation, would be great to get some help!

**Comment by eugenioamn** [comment]
Thank you! I've just done that. What do I need to do now? Here is the code, if needed:

`[![gitlocalized ](https://gitlocalize.com/repo/4238/pt-BR/badge.svg)](https://gitlocalize.com/repo/4238/pt-BR?utm_source=badge)`

**Comment by dwmkerr** [comment]
All done! You are a moderator of the `pt-BR` translation and should be able to add translations via GitLocalise! Thanks so much for the help :smile:
