### ISSUE TITLE
Add a moderation citation to "The Robustness Principle"

### ISSUE THREAD

**Issue by smoyer64** [dwmkerr/hacker-laws#265]
The Robustness Principle or Postel's law should include a citation to the ACM paper titled [The Robustness Principle Reconsidered](https://queue.acm.org/detail.cfm?id=1999945).  This paper (properly) describes the security flaws and other errors that can creep into a system that accepts an overly broad set of input.

**Comment by puremana** [comment]
Can close I think 👍

**Comment by dwmkerr** [comment]
TY!
