### ISSUE TITLE
Add Hanlon's razor

### ISSUE THREAD

**Issue by xp-vit** [dwmkerr/hacker-laws#286]
https://en.m.wikipedia.org/wiki/Hanlon%27s_razor#:~:text=Hanlon's%20razor%20is%20an%20aphorism,unlikely%20explanations%20for%20human%20behavior.

And as example of it all kind of Intel CPU failures.

**Comment by dwmkerr** [comment]
It's already in 😄 

https://github.com/dwmkerr/hacker-laws#hanlons-razor
