### ISSUE TITLE
Add the Dunning–Kruger effect

### ISSUE THREAD

**Issue by schoetbi** [dwmkerr/hacker-laws#300]
In the field of psychology, the Dunning–Kruger effect is a cognitive bias in which people with low ability at a task overestimate their ability

See wikipedia: [Dunning–Kruger effect](https://en.wikipedia.org/wiki/Dunning%E2%80%93Kruger_effect)

**Comment by dwmkerr** [comment]
Yep makes sense to include!

**Comment by akashchandwani** [comment]
Hi @dwmkerr , 

I have raised a PR for this, Could you please review and share your thoughts? 

https://github.com/dwmkerr/hacker-laws/pull/318
