### ISSUE TITLE
Law: Brooks' law 

### ISSUE THREAD

**Issue by rheh** [dwmkerr/hacker-laws#31]
It is worth considering the addition of Brooks' law.

https://en.m.wikipedia.org/wiki/Brooks%27s_law

**Comment by dwmkerr** [comment]
Great idea, thanks @rheh! Will add soon 👍

**Comment by aiboy** [comment]
@dwmkerr any progress on this one?

**Comment by dwmkerr** [comment]
Done, thanks @rheh!
