### ISSUE TITLE
Add Hacktoberfest Topic

### ISSUE THREAD

**Issue by puremana** [dwmkerr/hacker-laws#314]
I plan on adding some of the built up law suggestions in issues but now that Hacktoberfest is running it may be a good idea to take advantage of people willing to contribute by adding a Hacktoberfest topic to the repo.

Thanks for all your hard work as always!

**Comment by dwmkerr** [comment]
Great idea!

**Comment by puremana** [comment]
Bump reminder 😄

**Comment by puremana** [comment]
Not sure what happened but not relevant anymore as Hacktoberfest has finished so will close this issue.

**Comment by troyane** [comment]
Another one is approaching :D

**Comment by dwmkerr** [comment]
OK cool! What do we need to do to open it up?

**Comment by puremana** [comment]
I'm not sure if you need it this year

**Comment by troyane** [comment]
@dwmkerr AFAIK you just need to add respective topic https://github.com/topics/hacktoberfest to your repo.
Personally I'm still in progress with Ukrainian translation, so why not?
