### ISSUE TITLE
German translation (3rd time's the charm)

### ISSUE THREAD

**Issue by Florian-Rh** [dwmkerr/hacker-laws#341]
Hello Dave!
Firstly, thank you for this super cool and comprehensive collection. I run a bilingual german/english software development blog and I have already [referenced parts of your repository there](https://blog.rhein.me/en/posts/mindfulness-software-development-5/).
I saw that the german translation is somewhat dormant and the corresponding issue was closed last year.
I want to change that! Can you add me as language moderator? (https://gitlocalize.com/users/Florian-Rh)

**Comment by cblte** [comment]
Hey Florian, hello Dave.
Maybe I can help with that a little bit. Using the site quite often, but never actually looked at the German translation.

**Comment by dwmkerr** [comment]
Yes i'll add you now!

**Comment by dwmkerr** [comment]
Done! Please feel free to add yourself to the moderators list in the README file in the translators section :)

![image](https://user-images.githubusercontent.com/1926984/115186783-e3e84500-a114-11eb-974a-ffd2c72ee6f7.png)

**Comment by rafo** [comment]
@dwmkerr  Currently, the link on the main page to the German translation doesn't work.
