### ISSUE TITLE
build: create static site

### ISSUE THREAD

**Issue by dwmkerr** [dwmkerr/hacker-laws#61]
Create a simple static site from the README and publish. Link to new domain name.

Step 1: Simple README rendering (see comment below)

Step 2: Some more advanced options

- netlify
- mdx-go
- jekyll

Step 3: Consider some additional features:

- Law of the day?
- Flashcards?

**Comment by johnletey** [comment]
May I suggest [mdx-go](https://github.com/jxnblk/mdx-go)

**Comment by dwmkerr** [comment]
Thanks @johnletey will look into it!

**Comment by alexeyraspopov** [comment]
Another cheap and efficient option is to enable github pages for master branch. It uses README as a main page and applies pretty decent styles to it. (Here is an example: https://alexeyraspopov.github.io/flux-guidelines/)

**Comment by dwmkerr** [comment]
@alexeyraspopov I had no idea you could just directly render the `README` like that, awesome! I'll likely set that up as step one. Thanks so much!

**Comment by dwmkerr** [comment]
At the moment I think that the project works fine just as a plain old github project - if it looks like there's a lot of demand for a static site I will re-open the issue but I think I'll focus on more content for now instead!
