### ISSUE TITLE
Broken Window Theory

### ISSUE THREAD

**Issue by KKPMW** [dwmkerr/hacker-laws#70]
First heard about this in "The pragmatic programmer" book.

There is a wikipedia page on it: [Broken Window Theory](https://en.wikipedia.org/wiki/Broken_windows_theory) but it doesn't talk about software.

In short the theory states that when one broken/messy part is introduced to the system and left unfixed for a period of time people will stop caring about maintaining the quality in other areas within that system. In this way the perception about things being out of control grows and the entropy spreads. Other weaknesses are introduced until the whole system is abandoned.

The advice is given to put "fires" out as soon as they are detected and don't let one broken thing stay broken for long.

Possible references:

https://pragprog.com/the-pragmatic-programmer/extracts/software-entropy
https://blog.codinghorror.com/the-broken-window-theory/
https://opensourceforu.com/2011/05/joy-of-programming-broken-window-theory/

**Comment by dwmkerr** [comment]
Great idea, will get on it :)
