### ISSUE TITLE
This repo is cool. I has translated it to Chinese.

### ISSUE THREAD

**Issue by nusr** [dwmkerr/hacker-laws#86]
[https://github.com/nusr/hacker-laws-zh](https://github.com/nusr/hacker-laws-zh)

**Comment by dwmkerr** [comment]
Awesome! Can you help me include the Chinese text in the PR I've mentioned so that it looks like:

[Hacker Laws in Chinese / <Hacker Laws in Chinese, but written in Mandarin] so that I can include the link on the top of the repo?

**Comment by nusr** [comment]
ok
