### ISSUE TITLE
Gall's Law

### ISSUE THREAD

**Issue by tfnico** [dwmkerr/hacker-laws#90]
Had to think of this one when I saw this repo. I think fits pretty well. Just pasting quickly here as I'm on mobile:

https://en.m.wikipedia.org/wiki/John_Gall_(author)#Gall's_law

> A complex system that works is invariably found to have evolved from a simple system that worked. A complex system designed from scratch never works and cannot be patched up to make it work. You have to start over with a working simple system.

**Comment by dwmkerr** [comment]
Love it, will add it soon!
